language: node_js

dist: xenial

sudo: required

branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

node_js:
  - 4

cache:
  yarn: true

install:
  - npm install
  - npm run build

script:
  - make test
