language: node_js

sudo: required

branches:
  except:
    - /^v[0-9]/

services:
  - docker

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

node_js:
  - 4

cache:
  yarn: true

install:
  - yarn
  - npm run build
  - docker build -t galton .
  - docker run -d -p 127.0.0.1:5000:5000 --name galton galton "https://s3.amazonaws.com/metro-extracts.mapzen.com/moscow_russia.osm.pbf" car

script:
  - make test
  - docker ps | grep -q galton
